output "environment" {
  value = var.environment
}

output "worker_name" {
  value = "fork-api-${var.environment}"
}

output "app_url" {
  value = var.app_url
}

output "d1_database_name" {
  value = cloudflare_d1_database.fork.name
}

output "d1_database_id" {
  value       = cloudflare_d1_database.fork.id
  description = "wrangler.toml [[env.*.d1_databases]].database_id"
}

output "kv_namespace_id" {
  value       = cloudflare_workers_kv_namespace.fork.id
  description = "wrangler.toml [[env.*.kv_namespaces]].id"
}

output "wrangler_env_snippet" {
  value       = <<-EOT
    # Generated by Terraform — sync via: npm run infra:sync -- ${var.environment}
    [env.${var.environment}]
    name = "fork-api-${var.environment}"
    vars = { APP_URL = "${var.app_url}" }

    [[env.${var.environment}.d1_databases]]
    binding = "DB"
    database_name = "${cloudflare_d1_database.fork.name}"
    database_id = "${cloudflare_d1_database.fork.id}"
    migrations_dir = "packages/db/migrations"

    [[env.${var.environment}.kv_namespaces]]
    binding = "KV"
    id = "${cloudflare_workers_kv_namespace.fork.id}"
  EOT
  description = "Reference snippet for wrangler env block"
}
